version: '3.7'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: screech_db
    env_file:
      - ./.env.secret
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - main
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
    container_name: screech_app
    user: appuser
    env_file:
      - ./.env
      - ./.env.secret
    command: flask run --host 0.0.0.0
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - main

networks:
  main:

volumes:
  dbdata: