version: '3.7'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: screech_db
    env_file:
      - ./.env.secret
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - main
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
    container_name: screech_app
    user: appuser
    env_file:
      - ./.env
      - ./.env.secret
    command: gunicorn -b 0.0.0.0:5001 app.hello_fl:app --chdir /
    volumes:
      - ./app:/app
    depends_on:
      - db
    expose:
      - 5001
    networks:
      - main

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - main

networks:
  main:

volumes:
  dbdata: